In [11]:
import pandas as pd
df=pd.read_csv('Cleaned.csv')
df.shape

(8114, 30)

In [12]:
df.isna().sum()

App ID                               0
state_code                           0
county_code                          0
derived_loan_product_type            0
derived_dwelling_category            0
derived_race                         0
derived_sex                          0
action_taken                         0
purchaser_type                       0
preapproval                          0
loan_type                            0
loan_purpose                         0
lien_status                          0
business_or_commercial_purpose       0
loan_amount                          0
combined_loan_to_value_ratio      1388
interest_rate                     1898
rate_spread                       1899
hoepa_status                         0
total_loan_costs                  2055
total_points_and_fees             8114
origination_charges               2055
discount_points                   3236
lender_credits                    8092
property_value                     700
occupancy_type                       0
income                             724
debt_to_income_ratio              1368
applicant_credit_score_type          0
applicant_ethnicity_1                0
dtype: int64

In [15]:
df = df.drop(columns = ['lender_credits', 'total_points_and_fees', 'rate_spread', 'discount_points'])

In [16]:
df = df.dropna()
df.head()

,App ID,state_code,county_code,derived_loan_product_type,derived_dwelling_category,derived_race,derived_sex,action_taken,purchaser_type,preapproval,...,interest_rate,hoepa_status,total_loan_costs,origination_charges,property_value,occupancy_type,income,debt_to_income_ratio,applicant_credit_score_type,applicant_ethnicity_1
6,558,MO,29097,FHA:First Lien,Single Family (1-4 Units):Site-Built,White,Male,1,9,2,...,3.625,2,5491.27,1185.00,175000.0,1,115.0,20%-<30%,2,2
16,568,MO,29189,FHA:First Lien,Single Family (1-4 Units):Site-Built,Black or African American,Male,1,2,2,...,3.750,2,5758.48,995.00,155000.0,1,60.0,44,1,2
18,570,MO,29183,FHA:First Lien,Single Family (1-4 Units):Site-Built,Black or African American,Male,1,2,2,...,3.625,2,5463.26,0.00,245000.0,1,63.0,50%-60%,3,2
32,766,MO,29077,FHA:First Lien,Single Family (1-4 Units):Site-Built,White,Female,1,2,2,...,4.125,2,4969.86,625.66,145000.0,1,33.0,41,1,2
33,768,MO,29161,VA:First Lien,Single Family (1-4 Units):Site-Built,White,Joint,1,2,2,...,3.750,2,2828.38,972.09,185000.0,1,89.0,38,2,2

In [6]:
data = Biases.copy()                               # Create duplicate of data
data = data.replace(r'^s*$', float('NaN'), regex = True)  # Replace blanks by NaN
print(data)

      App ID state_code  county_code derived_loan_product_type  \
0        549         MO        29099            FHA:First Lien
1        550         MO        29099        FSA/RHS:First Lien
2        551         MO        29189             VA:First Lien
3        552         MO        29099        FSA/RHS:First Lien
4        553         MO        29047            FHA:First Lien
...      ...        ...          ...                       ...
8109   14100         MO        29019   Conventional:First Lien
8110   14103         MO        29095   Conventional:First Lien
8111   14104         MO        29007   Conventional:First Lien
8112   14107         MO        29099             VA:First Lien
8113   14108         MO        29209   Conventional:First Lien

                 derived_dwelling_category               derived_race  \
0     Single Family (1-4 Units):Site-Built                      White
1     Single Family (1-4 Units):Site-Built                      White
2     Single Family (1-4 Units):Site-Built  Black or African American
3     Single Family (1-4 Units):Site-Built                      White
4     Single Family (1-4 Units):Site-Built  Black or African American
...                                    ...                        ...
8109  Single Family (1-4 Units):Site-Built                      White
8110  Single Family (1-4 Units):Site-Built                      White
8111  Single Family (1-4 Units):Site-Built                      White
8112  Single Family (1-4 Units):Site-Built                      White
8113  Single Family (1-4 Units):Site-Built                      White

     derived_sex  action_taken  purchaser_type  preapproval  ...  \
0          Joint             3               0            2  ...
1          Joint             1               2            2  ...
2           Male             3               0            2  ...
3           Male             3               0            2  ...
4         Female             3               0            2  ...
...          ...           ...             ...          ...  ...
8109        Male             1               1            2  ...
8110       Joint             1               3            2  ...
8111       Joint             1               1            2  ...
8112       Joint             1               2            2  ...
8113       Joint             3               0            2  ...

      total_points_and_fees  origination_charges  discount_points  \
0                       NaN                  NaN              NaN
1                       NaN             10016.24          7393.92
2                       NaN                  NaN              NaN
3                       NaN                  NaN              NaN
4                       NaN                  NaN              NaN
...                     ...                  ...              ...
8109                    NaN              2881.88          1631.88
8110                    NaN              4990.00          3740.00
8111                    NaN              4576.00          4576.00
8112                    NaN              2569.20          1455.99
8113                    NaN                  NaN              NaN

      lender_credits  property_value  occupancy_type  income  \
0                NaN        115000.0               1    49.0
1               44.5             NaN               1     NaN
2                NaN         95000.0               1    44.0
3                NaN             NaN               1     NaN
4                NaN        115000.0               1    34.0
...              ...             ...             ...     ...
8109             NaN        315000.0               1    94.0
8110             NaN        305000.0               1   163.0
8111             NaN        205000.0               1    59.0
8112             NaN        145000.0               1     NaN
8113             NaN        605000.0               1    89.0

      debt_to_income_ratio  applicant_credit_score_type  applicant_ethnicity_1
0                       40                            1                      2
1                      NaN                            3                      2
2                       36                            1                      2
3                      NaN                            3                      2
4                  50%-60%                            3                      1
...                    ...                          ...                    ...
8109              30%-<36%                            3                      2
8110                  <20%                            3                      2
8111                    41                            3                      2
8112                   NaN                            2                      2
8113              20%-<30%                            2                      2

[8114 rows x 30 columns]

In [10]:
data = data.dropna()
print (data)

Empty DataFrame
Columns: [App ID, state_code, county_code, derived_loan_product_type, derived_dwelling_category, derived_race, derived_sex, action_taken, purchaser_type, preapproval, loan_type, loan_purpose, lien_status, business_or_commercial_purpose, loan_amount, combined_loan_to_value_ratio, interest_rate, rate_spread, hoepa_status, total_loan_costs, total_points_and_fees, origination_charges, discount_points, lender_credits, property_value, occupancy_type, income, debt_to_income_ratio, applicant_credit_score_type, applicant_ethnicity_1]
Index: []

[0 rows x 30 columns]

In [8]:
data2.to_csv('cleaned-final.csv')